"""
routers/interview.py
---------------------
POST /interview/generate -> role-specific interview questions
(technical / behavioral / HR), generated by the LLM with a mock fallback.
Each session is saved to SQLite for the logged-in user.
"""

import json

from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session

from ..auth import get_current_user
from ..database import get_db
from ..models import InterviewSession, User
from ..schemas import (
    InterviewRequest,
    InterviewResponse,
    MockInterviewRequest,
    MockInterviewResponse,
)
from ..services import llm

router = APIRouter(prefix="/interview", tags=["interview"])


@router.post("/generate", response_model=InterviewResponse)
def generate(
    payload: InterviewRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    result = llm.generate_questions(
        role=payload.role,
        resume_text=payload.resume_text,
        num=payload.num_questions,
    )

    session = InterviewSession(
        user_id=current_user.id,
        role=payload.role,
        questions_json=json.dumps(result),
    )
    db.add(session)
    db.commit()
    db.refresh(session)

    return InterviewResponse(
        role=payload.role,
        technical=result["technical"],
        behavioral=result["behavioral"],
        hr=result["hr"],
        session_id=session.id,
    )


@router.post("/mock", response_model=MockInterviewResponse)
def mock_interview(
    payload: MockInterviewRequest,
    current_user: User = Depends(get_current_user),
):
    """One turn of a chat-style mock interview. Frontend keeps the history and
    sends it each turn; we return the interviewer's next message."""
    history = [{"role": m.role, "content": m.content} for m in payload.messages]
    reply = llm.mock_interview_reply(payload.role, history)
    return MockInterviewResponse(reply=reply)
