// notesPdf.js
// -----------
// Export AI-generated study notes as a clean, printable PDF.

import { jsPDF } from "jspdf";

export function downloadNotesPdf(note) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 48;
  const maxW = pageW - 2 * margin;
  let y = margin;

  const advance = (amount) => {
    y += amount;
    if (y > pageH - margin) {
      doc.addPage();
      y = margin;
    }
  };

  const write = (text, { size = 11, style = "normal", color = [40, 40, 50], gap = 15 } = {}) => {
    doc.setFont("helvetica", style);
    doc.setFontSize(size);
    doc.setTextColor(...color);
    const lines = doc.splitTextToSize(text, maxW);
    lines.forEach((ln) => {
      doc.text(ln, margin, y);
      advance(gap);
    });
  };

  // Header band
  doc.setFillColor(79, 70, 229);
  doc.rect(0, 0, pageW, 64, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("CareerBoost AI — Study Notes", margin, 40);
  y = 92;

  write(note.title, { size: 18, style: "bold", color: [20, 20, 30], gap: 24 });
  if (note.summary) write(note.summary, { color: [90, 90, 100], gap: 15 });
  advance(8);

  (note.sections || []).forEach((sec) => {
    write(sec.heading, { size: 13, style: "bold", color: [79, 70, 229], gap: 18 });
    (sec.points || []).forEach((p) => write("• " + p, { gap: 15 }));
    advance(6);
  });

  if (note.key_terms?.length) {
    write("Key Terms", { size: 13, style: "bold", color: [79, 70, 229], gap: 18 });
    note.key_terms.forEach((t) =>
      write(`${t.term}: ${t.definition}`, { gap: 15 })
    );
    advance(6);
  }

  if (note.questions?.length) {
    write("Practice Questions", { size: 13, style: "bold", color: [79, 70, 229], gap: 18 });
    note.questions.forEach((q, i) => write(`${i + 1}. ${q}`, { gap: 15 }));
  }

  doc.setFontSize(9);
  doc.setTextColor(150, 150, 160);
  doc.text(`Generated by CareerBoost AI on ${new Date().toLocaleDateString()}`, margin, pageH - 24);

  doc.save(`notes-${(note.topic || "study").replace(/\s+/g, "-").slice(0, 40)}.pdf`);
}
