// reportPdf.js
// ------------
// Builds a nicely formatted PDF of a resume-analysis report using jsPDF.
// Called from the Analyzer page's "Download PDF" button.

import { jsPDF } from "jspdf";

export function downloadReportPdf(report) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 48;
  let y = margin;

  // Move down, adding a new page if we run out of room.
  const advance = (amount) => {
    y += amount;
    if (y > pageH - margin) {
      doc.addPage();
      y = margin;
    }
  };

  // Header band
  doc.setFillColor(79, 70, 229); // brand indigo
  doc.rect(0, 0, pageW, 70, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("CareerBoost AI — Resume Report", margin, 44);
  y = 100;

  // Title + overall score
  doc.setTextColor(20, 20, 30);
  doc.setFontSize(13);
  doc.setFont("helvetica", "normal");
  doc.text(`Role: ${report.job_title || "—"}`, margin, y);
  advance(24);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(34);
  doc.setTextColor(79, 70, 229);
  doc.text(`${Math.round(report.overall_score)} / 100`, margin, y);
  doc.setFontSize(11);
  doc.setTextColor(120, 120, 130);
  doc.setFont("helvetica", "normal");
  doc.text("Overall ATS score", margin, y + 16);
  advance(40);

  // Sub-scores
  const subs = [
    ["Skills match", report.skills_match],
    ["Experience relevance", report.experience_relevance],
    ["Keyword coverage", report.keyword_coverage],
    ["Format & readability", report.format_readability],
    ["Semantic match (embeddings)", report.semantic_match_score],
    ["LLM rubric score", report.llm_overall_score],
  ];
  doc.setTextColor(20, 20, 30);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Score breakdown", margin, y);
  advance(20);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  subs.forEach(([label, val]) => {
    if (val == null) return;
    doc.setTextColor(60, 60, 70);
    doc.text(label, margin, y);
    // simple bar
    const barX = margin + 230;
    const barW = pageW - margin - barX;
    doc.setFillColor(230, 232, 240);
    doc.rect(barX, y - 8, barW, 8, "F");
    doc.setFillColor(79, 70, 229);
    doc.rect(barX, y - 8, (barW * Math.max(0, Math.min(100, val))) / 100, 8, "F");
    doc.setTextColor(20, 20, 30);
    doc.text(`${Math.round(val)}`, pageW - margin, y, { align: "right" });
    advance(20);
  });
  advance(10);

  // A reusable list section
  const section = (title, items, color) => {
    if (!items || items.length === 0) return;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(...color);
    doc.text(title, margin, y);
    advance(20);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(50, 50, 60);
    items.forEach((item, i) => {
      const prefix = title.startsWith("Suggestions") ? `${i + 1}. ` : "• ";
      const lines = doc.splitTextToSize(prefix + item, pageW - 2 * margin);
      lines.forEach((ln) => {
        doc.text(ln, margin, y);
        advance(16);
      });
    });
    advance(10);
  };

  section("Missing keywords", report.missing_keywords, [200, 40, 40]);
  section("Strengths", report.strengths, [30, 140, 70]);
  section("Suggestions", report.suggestions, [79, 70, 229]);

  // Footer
  doc.setFontSize(9);
  doc.setTextColor(150, 150, 160);
  doc.text(
    `Generated by CareerBoost AI on ${new Date().toLocaleDateString()}`,
    margin,
    pageH - 24
  );

  doc.save(`CareerBoost-report-${(report.job_title || "resume").replace(/\s+/g, "-")}.pdf`);
}
